use_frameworks!

platform :ios, '8.0'

target 'xhwXNIMDemo_Example' do
  pod 'xhwXNIMDemo', :path => '../'

  target 'xhwXNIMDemo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
